# Generated by Django 2.0.5 on 2018-07-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPvmgBuffer',
            fields=[
                ('datatime', models.DateTimeField(db_column='DATATIME', primary_key=True, serialize=False)),
                ('systemcode', models.CharField(db_column='SYSTEMCODE', max_length=32)),
                ('nbqgl1', models.DecimalField(blank=True, db_column='NBQGL1', decimal_places=4, max_digits=15, null=True)),
                ('nbqgl2', models.DecimalField(blank=True, db_column='NBQGL2', decimal_places=4, max_digits=15, null=True)),
                ('nbqgl3', models.DecimalField(blank=True, db_column='NBQGL3', decimal_places=4, max_digits=15, null=True)),
                ('nbqgl4', models.DecimalField(blank=True, db_column='NBQGL4', decimal_places=4, max_digits=15, null=True)),
                ('nbqgl5', models.DecimalField(blank=True, db_column='NBQGL5', decimal_places=4, max_digits=15, null=True)),
                ('nbqgl6', models.DecimalField(blank=True, db_column='NBQGL6', decimal_places=4, max_digits=15, null=True)),
                ('nbqgl7', models.DecimalField(blank=True, db_column='NBQGL7', decimal_places=4, max_digits=15, null=True)),
                ('nbqgl8', models.DecimalField(blank=True, db_column='NBQGL8', decimal_places=4, max_digits=15, null=True)),
                ('nbqgl9', models.DecimalField(blank=True, db_column='NBQGL9', decimal_places=4, max_digits=15, null=True)),
                ('fdzgl', models.DecimalField(blank=True, db_column='FDZGL', decimal_places=4, max_digits=15, null=True)),
                ('ljfdl', models.DecimalField(blank=True, db_column='LJFDL', decimal_places=4, max_digits=15, null=True)),
                ('jrfdl', models.DecimalField(blank=True, db_column='JRFDL', decimal_places=4, max_digits=15, null=True)),
                ('hjwd', models.DecimalField(blank=True, db_column='HJWD', decimal_places=4, max_digits=15, null=True)),
                ('rz', models.DecimalField(blank=True, db_column='RZ', decimal_places=4, max_digits=15, null=True)),
                ('fs', models.DecimalField(blank=True, db_column='FS', decimal_places=4, max_digits=15, null=True)),
                ('fx', models.DecimalField(blank=True, db_column='FX', decimal_places=4, max_digits=15, null=True)),
                ('co2jp', models.DecimalField(blank=True, db_column='CO2JP', decimal_places=4, max_digits=15, null=True)),
                ('fzhdl', models.DecimalField(blank=True, db_column='FZHDL', decimal_places=4, max_digits=15, null=True)),
                ('fzzgl', models.DecimalField(blank=True, db_column='FZZGL', decimal_places=4, max_digits=15, null=True)),
                ('llxyggl', models.DecimalField(blank=True, db_column='LLXYGGL', decimal_places=4, max_digits=15, null=True)),
                ('llxwggl', models.DecimalField(blank=True, db_column='LLXWGGL', decimal_places=4, max_digits=15, null=True)),
                ('pcsscgl', models.DecimalField(blank=True, db_column='PCSSCGL', decimal_places=4, max_digits=15, null=True)),
                ('pcspl', models.DecimalField(blank=True, db_column='PCSPL', decimal_places=4, max_digits=15, null=True)),
                ('lizdy', models.DecimalField(blank=True, db_column='LIZDY', decimal_places=4, max_digits=15, null=True)),
                ('lizdl', models.DecimalField(blank=True, db_column='LIZDL', decimal_places=4, max_digits=15, null=True)),
                ('lisoc', models.DecimalField(blank=True, db_column='LISOC', decimal_places=4, max_digits=15, null=True)),
                ('lisoh', models.DecimalField(blank=True, db_column='LISOH', decimal_places=4, max_digits=15, null=True)),
                ('work_mode', models.DecimalField(blank=True, db_column='WORK_MODE', decimal_places=0, max_digits=2, null=True)),
                ('work_zt', models.CharField(blank=True, db_column='WORK_ZT', max_length=128, null=True)),
                ('bj', models.CharField(blank=True, db_column='BJ', max_length=128, null=True)),
                ('dataflag', models.DecimalField(db_column='DATAFLAG', decimal_places=0, max_digits=2)),
            ],
            options={
                'db_table': 'data_pvmg_buffer',
                'managed': False,
            },
        ),
    ]
