# Generated by Django 2.0.5 on 2018-07-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCtyd',
            fields=[
                ('datatime', models.DateTimeField(db_column='DATATIME', primary_key=True, serialize=False)),
                ('systemcode', models.CharField(db_column='SYSTEMCODE', max_length=32)),
                ('edsugl', models.DecimalField(blank=True, db_column='EDSUGL', decimal_places=4, max_digits=15, null=True)),
                ('sclx', models.DecimalField(blank=True, db_column='SCLX', decimal_places=0, max_digits=2, null=True)),
                ('rfdl', models.DecimalField(blank=True, db_column='RFDL', decimal_places=4, max_digits=15, null=True)),
                ('zyxsj', models.DecimalField(blank=True, db_column='ZYXSJ', decimal_places=4, max_digits=15, null=True)),
                ('jnkqwd', models.DecimalField(blank=True, db_column='JNKQWD', decimal_places=4, max_digits=15, null=True)),
                ('zldl1', models.DecimalField(blank=True, db_column='ZLDL1', decimal_places=4, max_digits=15, null=True)),
                ('zldl2', models.DecimalField(blank=True, db_column='ZLDL2', decimal_places=4, max_digits=15, null=True)),
                ('zldl3', models.DecimalField(blank=True, db_column='ZLDL3', decimal_places=4, max_digits=15, null=True)),
                ('zldl4', models.DecimalField(blank=True, db_column='ZLDL4', decimal_places=4, max_digits=15, null=True)),
                ('zldy1', models.DecimalField(blank=True, db_column='ZLDY1', decimal_places=4, max_digits=15, null=True)),
                ('zldy2', models.DecimalField(blank=True, db_column='ZLDY2', decimal_places=4, max_digits=15, null=True)),
                ('zldy3', models.DecimalField(blank=True, db_column='ZLDY3', decimal_places=4, max_digits=15, null=True)),
                ('zldy4', models.DecimalField(blank=True, db_column='ZLDY4', decimal_places=4, max_digits=15, null=True)),
                ('zzlgl', models.DecimalField(blank=True, db_column='ZZLGL', decimal_places=4, max_digits=15, null=True)),
                ('dl_a', models.DecimalField(blank=True, db_column='DL_A', decimal_places=4, max_digits=15, null=True)),
                ('dl_b', models.DecimalField(blank=True, db_column='DL_B', decimal_places=4, max_digits=15, null=True)),
                ('dl_c', models.DecimalField(blank=True, db_column='DL_C', decimal_places=4, max_digits=15, null=True)),
                ('dy_a', models.DecimalField(blank=True, db_column='DY_A', decimal_places=4, max_digits=15, null=True)),
                ('dy_b', models.DecimalField(blank=True, db_column='DY_B', decimal_places=4, max_digits=15, null=True)),
                ('dy_c', models.DecimalField(blank=True, db_column='DY_C', decimal_places=4, max_digits=15, null=True)),
                ('zyggl', models.DecimalField(blank=True, db_column='ZYGGL', decimal_places=4, max_digits=15, null=True)),
                ('dwpl', models.DecimalField(blank=True, db_column='DWPL', decimal_places=4, max_digits=15, null=True)),
                ('nbqxl', models.DecimalField(blank=True, db_column='NBQXL', decimal_places=4, max_digits=15, null=True)),
                ('zt', models.CharField(blank=True, db_column='ZT', max_length=128, null=True)),
                ('bj', models.CharField(blank=True, db_column='BJ', max_length=128, null=True)),
                ('work_zt', models.DecimalField(db_column='WORK_ZT', decimal_places=0, max_digits=2)),
                ('dataflag', models.DecimalField(db_column='DATAFLAG', decimal_places=0, max_digits=2)),
                ('zfdl', models.DecimalField(blank=True, db_column='ZFDL', decimal_places=4, max_digits=15, null=True)),
                ('intzt', models.DecimalField(blank=True, db_column='INTZT', decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'data_ctyd_buffer',
                'managed': False,
            },
        ),
    ]
