# Generated by Django 2.0.5 on 2018-07-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pvdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityid', models.CharField(db_column='CityID', max_length=6)),
                ('updatetime', models.DateTimeField(db_column='UpdateTime')),
                ('pcbid', models.IntegerField(db_column='PcbID')),
                ('channelid', models.IntegerField(db_column='ChannelID')),
                ('batid', models.IntegerField(blank=True, db_column='BatID', null=True)),
                ('u', models.FloatField(blank=True, db_column='U', null=True)),
                ('i', models.FloatField(blank=True, db_column='I', null=True)),
                ('p', models.FloatField(blank=True, db_column='P', null=True)),
                ('t', models.FloatField(blank=True, db_column='T', null=True)),
                ('v12', models.FloatField(blank=True, db_column='V12', null=True)),
                ('v5', models.FloatField(blank=True, db_column='V5', null=True)),
                ('devicetime', models.CharField(blank=True, db_column='DeviceTime', max_length=20, null=True)),
                ('pcor', models.FloatField(blank=True, db_column='Pcor', null=True)),
            ],
            options={
                'db_table': 'pvdata',
                'managed': False,
            },
        ),
    ]
