# Generated by Django 2.0.5 on 2018-07-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSpgsBuffer',
            fields=[
                ('datatime', models.CharField(db_column='DATATIME', max_length=22, primary_key=True, serialize=False)),
                ('systemcode', models.CharField(db_column='SYSTEMCODE', max_length=6)),
                ('nbqgl1', models.DecimalField(blank=True, db_column='NBQGL1', decimal_places=4, max_digits=15, null=True)),
                ('nbqgl2', models.DecimalField(blank=True, db_column='NBQGL2', decimal_places=4, max_digits=15, null=True)),
                ('nbqgl3', models.DecimalField(blank=True, db_column='NBQGL3', decimal_places=4, max_digits=15, null=True)),
                ('nbqgl4', models.DecimalField(blank=True, db_column='NBQGL4', decimal_places=4, max_digits=15, null=True)),
                ('nbqgl5', models.DecimalField(blank=True, db_column='NBQGL5', decimal_places=4, max_digits=15, null=True)),
                ('nbqgl6', models.DecimalField(blank=True, db_column='NBQGL6', decimal_places=4, max_digits=15, null=True)),
                ('nbqgl7', models.DecimalField(blank=True, db_column='NBQGL7', decimal_places=4, max_digits=15, null=True)),
                ('nbqgl8', models.DecimalField(blank=True, db_column='NBQGL8', decimal_places=4, max_digits=15, null=True)),
                ('nbqgl9', models.DecimalField(blank=True, db_column='NBQGL9', decimal_places=4, max_digits=15, null=True)),
                ('nbqgl10', models.DecimalField(blank=True, db_column='NBQGL10', decimal_places=4, max_digits=15, null=True)),
                ('fdzgl', models.DecimalField(blank=True, db_column='FDZGL', decimal_places=4, max_digits=15, null=True)),
                ('ljfdl', models.DecimalField(blank=True, db_column='LJFDL', decimal_places=4, max_digits=15, null=True)),
                ('drfdl', models.DecimalField(blank=True, db_column='DRFDL', decimal_places=4, max_digits=15, null=True)),
                ('zjrl', models.DecimalField(blank=True, db_column='ZJRL', decimal_places=4, max_digits=15, null=True)),
                ('hjwd', models.DecimalField(blank=True, db_column='HJWD', decimal_places=4, max_digits=15, null=True)),
                ('fz', models.DecimalField(blank=True, db_column='FZ', decimal_places=4, max_digits=15, null=True)),
                ('fs', models.DecimalField(blank=True, db_column='FS', decimal_places=4, max_digits=15, null=True)),
                ('fx', models.DecimalField(blank=True, db_column='FX', decimal_places=4, max_digits=15, null=True)),
                ('co2jp', models.DecimalField(blank=True, db_column='CO2JP', decimal_places=4, max_digits=15, null=True)),
                ('bzmjp', models.DecimalField(blank=True, db_column='BZMJP', decimal_places=4, max_digits=15, null=True)),
                ('ntfcjp', models.DecimalField(blank=True, db_column='NTFCJP', decimal_places=4, max_digits=15, null=True)),
                ('nojp', models.DecimalField(blank=True, db_column='NOJP', decimal_places=4, max_digits=15, null=True)),
                ('h2ojp', models.DecimalField(blank=True, db_column='H2OJP', decimal_places=4, max_digits=15, null=True)),
                ('work_mode', models.DecimalField(blank=True, db_column='WORK_MODE', decimal_places=0, max_digits=2, null=True)),
                ('dataflag', models.DecimalField(db_column='DATAFLAG', decimal_places=0, max_digits=2)),
            ],
            options={
                'db_table': 'data_spgs_buffer',
                'managed': False,
            },
        ),
    ]
