# Generated by Django 2.0.5 on 2018-07-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnoCtydBuffer',
            fields=[
                ('title', models.CharField(blank=True, db_column='TITLE', max_length=50, null=True)),
                ('target', models.CharField(blank=True, db_column='TARGET', max_length=20, null=True)),
                ('connent', models.TextField(blank=True, db_column='CONNENT', null=True)),
                ('author', models.CharField(blank=True, db_column='AUTHOR', max_length=20, null=True)),
                ('annotime', models.DateTimeField(db_column='ANNOTIME', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'anno_ctyd_buffer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BasicRole',
            fields=[
                ('roleid', models.CharField(db_column='ROLEID', max_length=32, primary_key=True, serialize=False)),
                ('rolename', models.CharField(db_column='ROLENAME', max_length=32)),
                ('remark', models.CharField(blank=True, db_column='REMARK', max_length=128, null=True)),
                ('candelete', models.DecimalField(db_column='CANDELETE', decimal_places=0, max_digits=1)),
                ('sortindex', models.DecimalField(db_column='SORTINDEX', decimal_places=0, max_digits=4)),
            ],
            options={
                'db_table': 'basic_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BasicUser',
            fields=[
                ('userid', models.CharField(db_column='USERID', max_length=32, primary_key=True, serialize=False)),
                ('roleid', models.CharField(blank=True, db_column='ROLEID', max_length=32, null=True)),
                ('usercode', models.CharField(db_column='USERCODE', max_length=32)),
                ('username', models.CharField(db_column='USERNAME', max_length=32)),
                ('psw', models.CharField(db_column='PSW', max_length=128)),
                ('pswsalt', models.CharField(db_column='PSWSALT', max_length=128)),
                ('remark', models.CharField(blank=True, db_column='REMARK', max_length=128, null=True)),
                ('createdate', models.DateTimeField(db_column='CREATEDATE')),
                ('islocked', models.DecimalField(db_column='ISLOCKED', decimal_places=0, max_digits=1)),
                ('candelete', models.DecimalField(db_column='CANDELETE', decimal_places=0, max_digits=1)),
            ],
            options={
                'db_table': 'basic_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devicecode', models.CharField(db_column='DEVICECODE', max_length=32)),
                ('systemtype', models.CharField(db_column='SYSTEMTYPE', max_length=32)),
                ('device', models.CharField(blank=True, db_column='DEVICE', max_length=32, null=True)),
                ('devicename', models.CharField(blank=True, db_column='DEVICENAME', max_length=128, null=True)),
                ('sortindex', models.DecimalField(blank=True, db_column='SORTINDEX', decimal_places=0, max_digits=4, null=True)),
                ('remark', models.CharField(blank=True, db_column='REMARK', max_length=128, null=True)),
            ],
            options={
                'db_table': 'device_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PowerStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systemtype', models.CharField(blank=True, db_column='systemType', max_length=255, null=True)),
            ],
            options={
                'db_table': 'power_station',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SystemParam',
            fields=[
                ('systemtype', models.CharField(db_column='SYSTEMTYPE', max_length=32)),
                ('paramcode', models.CharField(db_column='PARAMCODE', max_length=32)),
                ('paramname', models.CharField(db_column='PARAMNAME', max_length=128)),
                ('datatype', models.DecimalField(db_column='DATATYPE', decimal_places=0, max_digits=2)),
                ('paramtype', models.DecimalField(db_column='PARAMTYPE', decimal_places=0, max_digits=2)),
                ('unit', models.CharField(blank=True, db_column='UNIT', max_length=32, null=True)),
                ('ismonitor', models.DecimalField(db_column='ISMONITOR', decimal_places=0, max_digits=1)),
                ('canoper', models.DecimalField(db_column='CANOPER', decimal_places=0, max_digits=1)),
                ('sortindex', models.DecimalField(db_column='SORTINDEX', decimal_places=0, max_digits=4)),
                ('paramid', models.CharField(db_column='PARAMID', max_length=32, primary_key=True, serialize=False)),
                ('pos', models.DecimalField(blank=True, db_column='POS', decimal_places=0, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'system_param',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SystemType',
            fields=[
                ('systemtype', models.CharField(db_column='SYSTEMTYPE', max_length=32, primary_key=True, serialize=False)),
                ('systemname', models.CharField(db_column='SYSTEMNAME', max_length=128)),
                ('sortindex', models.DecimalField(db_column='SORTINDEX', decimal_places=0, max_digits=4)),
            ],
            options={
                'db_table': 'system_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Warnning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(db_column='DEVICE_TYPE', max_length=32)),
                ('name', models.CharField(db_column='NAME', max_length=50)),
                ('position', models.DecimalField(db_column='POSITION', decimal_places=0, max_digits=4)),
                ('systemtype', models.CharField(blank=True, db_column='SYSTEMTYPE', max_length=32, null=True)),
            ],
            options={
                'db_table': 'warnning',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WarnningHistory',
            fields=[
                ('tagid', models.DecimalField(blank=True, db_column='TAGID', decimal_places=0, max_digits=4, null=True)),
                ('systemtype', models.CharField(db_column='SYSTEMTYPE', max_length=32)),
                ('devicetype', models.CharField(db_column='DEVICETYPE', max_length=32)),
                ('paramid', models.CharField(blank=True, db_column='PARAMID', max_length=32, null=True)),
                ('starttime', models.DateTimeField(db_column='STARTTIME')),
                ('endtime', models.DateTimeField(blank=True, db_column='ENDTIME', null=True)),
                ('warningcontent', models.CharField(db_column='WARNINGCONTENT', max_length=128)),
                ('isend', models.DecimalField(db_column='ISEND', decimal_places=0, max_digits=1)),
                ('warningid', models.CharField(db_column='WARNINGID', max_length=32, primary_key=True, serialize=False)),
                ('postion', models.DecimalField(blank=True, db_column='POSTION', decimal_places=0, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'warnning_history',
                'managed': False,
            },
        ),
    ]
